#
# Ignore this file for now
#

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: smilr-tls-cert
spec:
  secretName: smilr-tls-cert
  commonName: 'smilr.7e28d40aaab5415089e6.northeurope.aksapp.io'
  dnsNames:
  - 'smilr.7e28d40aaab5415089e6.northeurope.aksapp.io'
  acme:
    config:
    - http01:
        ingressClass: addon-http-application-routing
      domains:
      - 'smilr.7e28d40aaab5415089e6.northeurope.aksapp.io'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer