apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory

    # !!! CHANGE THIS EMAIL ADDRESS !!!
    email: ben.coleman@microsoft.com
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}