#
# SAMPLE FILE - make a copy of this with your values in
#

# Change to blank string to pull from Docker Hub
registryPrefix: changeme.azurecr.io/

# Leave blank if not using DNS with your ingress
# Get the name of your AKS DNS zone by running `az network dns zone list -o table`
domainSuffix: smilr.changeme.changeme-region.aksapp.io

# If using cert-manager to issue TLS certs for HTTPS support 
# Leave blank if you haven't set up cert-manager to disable HTTPS
cmCertIssuer: 

dataApi:
  imageTag: latest
  replicas: 1
  mongoConnStr: 
  imagePullPolicy: Always

frontend:
  imageTag: latest
  replicas: 1
  imagePullPolicy: Always

mongo:
  usePersistence: false
