apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret-akseast
spec:
  secretName: tls-secret-akseast
  dnsNames:
  - akseast.evillgenius.com
  acme:
    config:
    - http01:
        ingressClass: nginx-external
      domains:
      - akseast.evillgenius.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer