apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret-agic
spec:
  secretName: tls-secret-agic
  dnsNames:
  - agic.evillgenius.com
  acme:
    config:
    - http01:
        ingressClass: azure/application-gateway
      domains:
      - agic.evillgenius.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer