apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-api
  template:
    metadata:
      labels:
        app: data-api
    spec:
      containers:
      - name: data-api-pod
        image: acrdemoev.azurecr.io/smilr/data-api
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: MONGO_CONNSTR
          valueFrom:
            secretKeyRef:
              name: cosmodb-secret
              key: connstr
      imagePullSecrets:
        - name: acr-auth
