apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-pod
        image: acrdemoev.azurecr.io/smilr/frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: API_ENDPOINT
            value: http://agic.evillgenius.com/api
      imagePullSecrets:
        - name: acr-auth
